# ================= CONFIG =================

GUI_REFRESH_MS = 500

OPC_UPDATE_RATE_MS = 1000
OPC_AUTO_RECONNECT_SEC = 5

PLC_POLL_INTERVAL_SEC = 1
PLC_AUTO_RECONNECT_SEC = 5

SIMULATION_MODE = True

# PLC (S7-1500 default)
PLC_IP = "192.168.0.1"
PLC_RACK = 0
PLC_SLOT = 1
